// Firebase entities (replacing Base44)
export {
  Workout,
  WeightEntry,
  ExerciseDefinition,
  ProgressPicture,
  Goal,
  Reminder,
  CalorieTracking,
  WeeklyTask,
  MonthlyGoal,
  CoachMenu,
  Recipe,
  WeightReminder,
  CoachMessage,
  PreMadeWorkout,
  WorkoutTemplate,
  UserGroup,
  Invitation,
  AdminActionLog,
  WaterTracking,
  WorkoutLog,
  Lecture,
  LectureView,
  FavoriteRecipe,
  CoachNotification,
  GroupWorkoutPlan,
  GroupReminder,
  GroupMessage,
  GroupEvent,
  WeeklyCheckin,
  ExerciseDefault,
  NotificationResponse,
  GeneratedReport,
  EventParticipation,
  MealTemplate,
  FoodItem,
  UserMeal,
  AdminMessage,
  ContractContent,
  TerminationFeedback,
  BoosterPlusTaskTemplate,
  BoosterPlusTask,
  WeeklyTaskTemplate
} from './firebaseEntities';

// Firebase auth (replacing Base44 auth)
export { User } from './firebaseAuth';