#!/usr/bin/env bash
# Set sendGroupEmail env from repo .env.local and deploy.
# Run from repo root: ./scripts/set-function-env.sh
# Requires: SMTP2GO_API_KEY in .env.local or .env

set -e
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Load only SMTP2GO_* vars from .env (safe for values with spaces; no 'source')
load_env() {
  local f="$1"
  [ ! -f "$f" ] && return
  while IFS= read -r line || [ -n "$line" ]; do
    [[ "$line" =~ ^#.*$ ]] && continue
    [[ "$line" =~ ^[[:space:]]*$ ]] && continue
    key="${line%%=*}"
    key="${key%%[[:space:]]*}"
    [[ "$key" != SMTP2GO_* ]] && continue
    val="${line#*=}"
    val="${val#\"}"; val="${val%\"}"; val="${val#\'}"; val="${val%\'}"
    [ -n "$key" ] && export "$key=$val"
  done < "$f"
}
if [ -f ".env.local" ]; then load_env ".env.local"; fi
if [ -f ".env" ]; then load_env ".env"; fi

if [ -z "$SMTP2GO_API_KEY" ]; then
  echo "Error: SMTP2GO_API_KEY not set. Add it to .env.local or .env in the repo root."
  exit 1
fi

# Write functions/.env so Firebase CLI loads it on deploy
mkdir -p functions
ENV_FILE="functions/.env"
echo "# Generated by scripts/set-function-env.sh - do not commit" > "$ENV_FILE"
echo "SMTP2GO_API_KEY=$SMTP2GO_API_KEY" >> "$ENV_FILE"
echo "SMTP2GO_SENDER_EMAIL=${SMTP2GO_SENDER_EMAIL:-result@roamjet.net}" >> "$ENV_FILE"
printf 'SMTP2GO_SENDER_NAME=%s\n' "${SMTP2GO_SENDER_NAME:-Vitrix App}" >> "$ENV_FILE"
echo "Wrote $ENV_FILE (gitignored)."

echo "Deploying sendGroupEmail (Firebase will use env from functions/.env)..."
firebase deploy --only functions:sendGroupEmail

echo "Done. sendGroupEmail will use SMTP2GO_API_KEY from functions/.env."
